### ISSUE TITLE
肉鸽异常

### ISSUE THREAD

**Issue by aleck099** [Misaka20004/Misaka_zdjl_series_for_Arknights#10]
如图
![f](https://user-images.githubusercontent.com/33549441/194686346-90085b58-36b9-4845-b1e5-d7d65eb55002.png)
明明有辅助券却说没有

**Comment by aleck099** [comment]
如果用滤镜：
![f2](https://user-images.githubusercontent.com/33549441/194686978-0a396c85-34b4-48a0-bbcc-173e7da5a2ea.PNG)
左图为PS的阀值算法，右图为自动精灵的黑白滤镜
你这自动精灵保熟吗，它算法有问题啊

不用滤镜也是寄
把范围放到下面“招募一个辅助干员”也识不出来

**Comment by Misaka20004** [comment]
这就是自动精灵的局限性了，你可以试试用mumu模拟器，不然的话，后续还有一些识别图片可能会出错（在逍遥模拟器上连识别文字都有可能会出错）。其他模拟器的问题应该较少，如果还有问题就需要你自己小修了
