### ISSUE TITLE
商店中偶发报错，提示“解析变量失败 Reference Error ...”

### ISSUE THREAD

**Issue by hczxpaul** [Misaka20004/Misaka_zdjl_series_for_Arknights#11]
![image](https://user-images.githubusercontent.com/18711629/196387974-d622496b-8595-4633-b26f-64bb12a73909.png)
mumu模拟器，水月肉鸽商店中偶尔会出现这个报错，然后脚本卡住不动

**Comment by Misaka20004** [comment]
已经修改了，重新下载一下。今天0:30左右改的

**Comment by Misaka20004** [comment]
我又该了一下，我找到原因了，是自动精灵官方升级了，他把“删除变量”这个动作的含义改了，变成了完全抹去这个变量，而不是原来的清理变量（改为undefined的状态）。现在我按照官方的指点，把我脚本里的“删除变量”改为“JS表达式-undefined”就没问题了，此外还把全部子脚本和母脚本合并了，以免出现其他子脚本识别不了全局变量导致解析变量失败
