### ISSUE TITLE
某些需要特定分队

### ISSUE THREAD

**Issue by 146928496z** [Misaka20004/Misaka_zdjl_series_for_Arknights#12]
需要骰子分队才会出 请问可以添加一个骰子分队吗

**Comment by Misaka20004** [comment]
可以，我可以先告诉你怎么改，在走廊的子脚本（进入方式：打开脚本，点击右上角的螺丝，然后点击内置的脚本，选择并编辑带“走廊”字样的脚本）里面把默认模式点击的位置改了就行了，不过这样的话，就别勾选分队了。今晚和另一个问题一起更新了

**Comment by 146928496z** [comment]
我选择指挥分队，然后把指挥分队改位置，但是鼠标点两次，第一次指令我找到了，第二次我没找到在哪里修改，我修改了之后，第二次还是会点击指挥，就不明白了，是我不太懂这个！谢谢大佬的指点，可以留个私方式吗，您加我也可以，65258211这是q，在q说微信吧

**Comment by 146928496z** [comment]
大佬你好，已经解决了谢谢大佬
