### ISSUE TITLE
Does this support global Arknights EN?

### ISSUE THREAD

**Issue by skzidan** [Misaka20004/Misaka_zdjl_series_for_Arknights#15]

**Comment by Misaka20004** [comment]
No, but if you understand Chinese, you can change the figure and characters on the execution condition(运行条件) of some steps, the structure of this script can be used for you.
This script was made in 自动精灵 app, and only can be operate in this app.

**Comment by skzidan** [comment]
can you recommend me some IS2(Integrated Strategies 2) scripts for Global Arknights EN server ? except MAA

**Comment by Misaka20004** [comment]
Sorry, I just know 自动精灵 and MAA, and these were enough lol

**Comment by skzidan** [comment]
I dont know why but MAA cant complete IS2(Integrated Strategies 2) endings, every time the run always failed.

**Comment by Misaka20004** [comment]
I think it can be run in global Arknights EN, I know some users meet some problem when he use MAA (CN), they might have some wrong settings of MAA, or forgot to choose Mizuki mode, or haven't open the page of Mizuki. Also, it may not support your mobile game simulator. Perhaps you are in the same condition.

ps: I don't know IS = Rougelike at first lol

**Comment by skzidan** [comment]
yep IS = Rougelike , and Mizuki mode doesnt release yet in global. I am assuming your scripts is for Mizuki Roguelike only?

**Comment by Misaka20004** [comment]
Did you mean that you can run Rougelike but it can't help you to pass the BOSS? I guess you can't use this function at first.

Actually, now I am 114 level and played this game for 1.5 years, and I log in Arknights everyday, but I haven't auto-pass the ending in MAA(may because I choose level 7). I think you don't have enough strong operators, and MAA is just a AI, he can't played like a human, he can't choose the best operator and put on the battlefield appropriately at one situations. There are so many situations and branches in the rougelike. 
MAA is just a tool to help you get rewards.

**Comment by Misaka20004** [comment]
I type this word for a long time lol
I didn't practice chatting with outlanders, you can ignore the above message.

**Comment by Misaka20004** [comment]
I released many script (each for different activity), including stationary security service (old mode and the new mode), phantom & crimson solitaire (IS1), and IS2, and TRIALS for nacigator #2,
but all of these were made in 自动精灵, and 自动精灵 only support Chinese.

You can rewrite my script, change the figure and characters on the execution condition(运行条件) of some steps, and then maybe you can auto Rougelike and take the rewards, but cannot pass the endings.
My script was very low, and I haven't learn to programming. My major was chemistry.

**Comment by skzidan** [comment]
Oh I see so your script cannot pass the endings. I mean I have atleast some of strong op's 
![image](https://user-images.githubusercontent.com/37244053/226406585-79cb9aad-5ef8-45ca-943a-514fa82579bd.png)
![image](https://user-images.githubusercontent.com/37244053/226406647-a82cb999-886a-444a-a74e-a555cab71e4f.png)
![image](https://user-images.githubusercontent.com/37244053/226406764-3841fdaa-fa2a-4590-849f-cbf6a57105f9.png)
No matter what I choose starting operator from MAA , it cant pass the endings. Like you said it just take rewards and restart the whole run. wish there was a tutorial how to make a script for the whole run in english language. If you also use MAA maybe you can help me to clear the roguelike?
