### ISSUE TITLE
错误：请确保在格里布矿场（0层）（门口）运行脚本。​

### ISSUE THREAD

**Issue by itheword** [Misaka20004/Misaka_zdjl_series_for_Arknights#4]
错误：请确保在格里布矿场（0层）（门口）运行脚本。​
![保全](https://user-images.githubusercontent.com/113843834/190912283-bef37a03-3f56-4ed0-afab-12b03428efe6.png)

**Comment by Misaka20004** [comment]
请使用mumu模拟器。这个问题好几个人遇到了，然后两个人说用mumu就没问题了。还有就是记得开root权限

**Comment by itheword** [comment]
已经用上了
