### ISSUE TITLE
难度4以上会卡死在招募医疗的选项上

### ISSUE THREAD

**Issue by buzz1129** [Misaka20004/Misaka_zdjl_series_for_Arknights#6]
难度4以上干员加费用了，前两个没有问题，但是医疗无法找到，不招募退出会有一个退出选项，这里会卡。我不是很明白，这个招募安塞尔不可以吗？临时医疗不一定在最后一页

**Comment by Misaka20004** [comment]
收到问题，正在尝试修改，我是考虑到安塞尔有人可能没练，另外战斗流程有检测临时医疗的头像，就没改

**Comment by Misaka20004** [comment]
已更新，你试试，如果没问题就告诉我或者直接把问题关闭

**Comment by buzz1129** [comment]
妥了，其实感觉医疗不招募也没啥问题，精一70能走到一层商店了，一层商店还没一直开后边得费老鼻子劲了
