### ISSUE TITLE
可能是个水月肉鸽脚本的一个小bug

### ISSUE THREAD

**Issue by butterfles** [Misaka20004/Misaka_zdjl_series_for_Arknights#8]
当在第一层遇到需要钥匙的得偿所愿时，会选中，然后到了是否使用钥匙时会卡一会儿，后面就直接左上角退出结束探索了

**Comment by Misaka20004** [comment]
因为带钥匙的关卡有作战、不期而遇、得偿所愿等，如果硬要解决这个问题，可能得想好一会儿，而且无法测试，经过我和其他人讨论之后，决定遇到这种关卡就退出，点进这种关卡是小概率事件，解决起来得不偿失
